backend = "glx";
vsync = true;

active-opacity = 0.85;
inactive-opacity = 0.80;
frame-opacity = 0.85;
inactive-opacity-override = false;

opacity-rule = [];

fading = true;
fade-delta = 2;
fade-in-step = 0.02;
fade-out-step = 0.02;
no-fading-openclose = false;
no-fading-destroyed-argb = true;

use-damage = true;

corner-radius = 12;

shadow = false;

blur: {
    method = "dual_kawase";
    strength = 5;
    background = true;
    background-frame = false;
    background-fixed = false;
};

blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENTS@:c"
];

wintypes:
{
    tooltip = { fade = true; shadow = false; opacity = 1.0; focus = true; full-shadow = false; };
    dock = { shadow = false; clip-shadow-above = true; };
    dnd = { shadow = false; };
    popup_menu = { opacity = 1.0; shadow = false; };
    dropdown_menu = { opacity = 1.0; shadow = false; };
};
